### ISSUE TITLE
Adding Slack Integration Support

### ISSUE THREAD

**Issue by abhinavcreed13** [matomatical/UoM-WAM-Spam#21]
It would be really helpful if we also support slack integration via webhooks or chatbots. 

The interface of slack integration is quite intuitive.

Is there any reason why slack support is not added yet?

I will try to play and see if I can enable that.

**Comment by matomatical** [comment]
Totally, I suppose the main reason is because nobody has expressed interest in this notification method yet. For example, I'm happy with email notifications myself (all other notification methods have been contributed by others).

The only issue I foresee is the notification going to a public channel (since results are considered sensitive information by some). I suppose it should go to a private message. It feels conceptually funny using slack like this, but if you would prefer that, then I'm happy to include the functionality in this app.

Therefore, I will happily review a pull request adding this feature if you build it. This will require (1) adding the implementation to the notify directory, (2) adding its configuration to the main script, and (3) adding instructions to the README. There are plenty of examples to follow. Good luck!

**Comment by abhinavcreed13** [comment]
Yeah, thanks for the steps.

Actually, webhooks support the integration to private channels also. There are also slack apps that are personally installed for you and then using slack commands you can ask for an update instantly or it can be pushed via app to your personal feed.

I did that in my internship so let me try to see if I can enable that. I will notify you after integration and testing.

**Comment by abhinavcreed13** [comment]
Also, how do you want me to go with this? Should I create a new branch with this feature request and then initiate a pull request for merging after testing?
Just wanted to be sure about the process of contribution.

**Comment by matomatical** [comment]
The contribution process is very informal. I recommend simply:

* Fork this repository
* Work in your fork, in the 'master' branch (or other branches as you see fit)
* Test your integration and instructions
* Open a pull request straight into this repo's 'master' branch
* I'll review and merge

I haven't put much thought into this. If you have a different preferred workflow, let me know, and I will consider it.

**Comment by abhinavcreed13** [comment]
Pull Request Opened #22

**Comment by matomatical** [comment]
Thanks, nice work. I plan to check it out first thing tomorrow.

**Comment by matomatical** [comment]
Merged #22
