### ISSUE TITLE
Consider using alternatives to selenium?

### ISSUE THREAD

**Issue by blueset** [matomatical/UoM-WAM-Spam#3]
Headless browsers could sometimes be resource consuming and difficult for some to install. A pure Python way of checking marks could be more feasible and require less binary dependencies.

Libraries like `requests` and `beautifulsoup4` or toolkits like `scrapy` could be a better alternative for this.

Didn't try multi-degree as I currently don't have one, but as what I have tried with, 3 requests should be sufficient to conduct the check. 

1. GET login page (for CSRF tokens and cookie)
2. POST login page (with CSRF, username and password)
3. GET result page

Cookie can be easily maintained with a `request.Session()` or equivalents.

P.S.: The current `prod.ss` system is really inefficient, especially when you try to load the entire breadth subjects list. The request body alone takes ~3 MB when switching between pages, which is totally unnecessary.

**Comment by matomatical** [comment]
Nice! I 100% agree. Selenium is a complete pain. I've used requests and bs4 before, so I'll look into that. I had thought it was necessary to use a browser to do things like login, etc. to a site with cookies and to manage the tokens for me, but I'll look into it further. I might even be able to get it to work for multi-degree pages (my use-case) since that uses javascript, but it's only to call a function called '`__doPostBack`' or something (suggesting it's really using POST). Are you willing to share any code you've tried so far to help me get started?

**Comment by matomatical** [comment]
Wow, I think I am in, with requests! That was easier than I thought. I'll try to get this into master today.

**Comment by matomatical** [comment]
Take a look at the code and let me know what you think, if you get a chance. Thanks for the inspiration :)
